# Generated by Django 5.1.7 on 2025-03-09 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_fake', models.BooleanField()),
                ('confidence', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Detection histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
